### ISSUE TITLE
Time Lock

### ISSUE THREAD

**Issue by Alistrago** [code-payments/code-timelock-explorer#1]
Today I tried paste my seed phrase but I see only "It can take a few minutes to derive all of your possible accounts and verify them against the Solana network. 
Please be patient." Nothing further

**Comment by Alistrago** [comment]
It showed me this ![image](https://github.com/code-wallet/timelock-explorer/assets/121552071/a6579ada-60cf-473a-b1dd-8a8a5b9af14c)

**Comment by zfedoran** [comment]
seems resolved with https://github.com/code-wallet/timelock-explorer/commit/77a01f685dbaa4f77c2c1ec1e59b4ce568c8a388
